version: '3.8'

services:
  app:
    build:
      context: .
    image: laravel8_test_workana_app
    container_name: laravel8_test_workana_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel8_test_workana_network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    ports:
      - "9000:9000"

  db:
    image: mysql:5.7
    container_name: laravel8_test_workana_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel8_test_workana_network

networks:
  laravel8_test_workana_network:

volumes:
  dbdata:

